# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elastico.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'elastico.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lastico.proto\x12\x08\x65lastico\x1a\x1bgoogle/protobuf/empty.proto\"o\n\x07IDProof\x12\n\n\x02IP\x18\x01 \x01(\t\x12\n\n\x02PK\x18\x02 \x01(\x0c\x12\x13\n\x0b\x43ommitteeId\x18\x03 \x01(\x0c\x12\x0b\n\x03PoW\x18\x04 \x01(\x0c\x12\x17\n\x0f\x45pochRandomness\x18\x05 \x01(\x0c\x12\x11\n\tPartOfNtw\x18\x06 \x01(\x08\x32K\n\x0cSetupService\x12;\n\x0eReceiveIDProof\x12\x11.elastico.IDProof\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elastico_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDPROOF']._serialized_start=57
  _globals['_IDPROOF']._serialized_end=168
  _globals['_SETUPSERVICE']._serialized_start=170
  _globals['_SETUPSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
